### ISSUE TITLE
Define relaton-collection schema

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-models#10]

**Comment by ronaldtse** [comment]
@opoudjis can I change this repo name to "relaton-models"?

**Comment by opoudjis** [comment]
Sure.

**Comment by opoudjis** [comment]
And you will need to, I don't have the privileges to.

**Comment by ronaldtse** [comment]
Just renamed to Relaton-models

**Comment by opoudjis** [comment]
Have not created the schema yet!

**Comment by opoudjis** [comment]
I've kept it completely simplistic:

````
relaton_collection = 
  element relaton-collection {
    attribute type { text }?,
    btitle, contributor*,
    docrelation*
}
````

No idea what the type attribute would be.

**Comment by ronaldtse** [comment]
@opoudjis Do we need an update to the UML model file to add `RelatonCollection`?

**Comment by opoudjis** [comment]
I thought about that. It's not clearly something needed in bibliographic record exchange, it has a much narrower purpose. A UML diagram would not hurt, I guess, it just would have to be presented separately from the rest of the model, with a disclaimer on what it is for. OK, reopening.
