### ISSUE TITLE
Port these elements into PlantUML code

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#12]
For @opoudjis 👍 

commit 26ae5ab0c6686a63814fa85da9a0f4919f28b27b
    add fetched element

commit 6ed69b4a800aa7992e2cf608da7242768d2b758a
    typed uri

commit c6df92f95d396630eb4fd5c6ce1b26cdd7bf4a0a
    added unchanged date; closes #8

Once this is done, delete the MDJ file.

**Comment by opoudjis** [comment]
So... we're no longer using StarUML?

**Comment by ronaldtse** [comment]
No, goodbye to StarUML, the unregistered version now generates images that says “unregistered”. And we want the same model definition for Metanorma content. 

So maybe we should add a script here to generate the PNGs for the README?
