### ISSUE TITLE
Model a website as a website

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#14]
Right now a website is modeled as an “electronic_resource” which is as vague as it can be. 

We should model a website as such and see if there are other types we should properly describe.

**Comment by ronaldtse** [comment]
I’ve submitted this to ISO 690 CD. let’s see what happens.

**Comment by opoudjis** [comment]
There are web pages, and there are web sites which are groupings of pages, preferably sharing a directory structure. The distinctive thing about websites is really just the use of http/https protocol and the presentation in HTML; I'm not convinced  other criteria are needed. The distinction between a forum and a static web page, for example, is secondary nowadays.

There are other types of electronic resource; those still published by ftp etc can stay electronic resources, and audio, video etc files are already described as such.

... Is there anything for me to do here? Do you want me to add "web resource" or "web site"/"web page" as a category?

**Comment by ronaldtse** [comment]
The point is "electronic resource" means anything. The current structure in 690 differentiates for example, "serials" against "electronic resources", which is actually comparing different categories.

What "electronic" means is the "medium". Serials are still serials, regardless on paper or electronic. A website however doesn't exist on paper.

Moving forward:

> ... Is there anything for me to do here? Do you want me to add "web resource" or "web site"/"web page" as a category?

Yes!

1.  Let's add a "web page" or "website" as a separate item.
2. Let's enrich the "Medium" model to support paper vs electronic. And if an information resource is electronic, it is possible to provide a URL to it.

**Comment by ronaldtse** [comment]
Isn't a "URI" a type of "realization"?

A work can exist as a concept, or as realizations. For example, a book can be in Audio Book format, mass paperback, hardcover, ePub, PDF, website, etc. I could technically cite from any of those. We want to make this clear in the models.

**Comment by opoudjis** [comment]
In FRBR, which is conceptually useful here, electronic resources are manifestations. FRBR have a hierarchy of four levels of abstraction, and we have pretty much already used them in a modelling: a work, a version (eg edition), a manifestation or format, and an instance (single physical copy)

**Comment by ronaldtse** [comment]
YES! We want to think about FRBR. MARC's successor BibFRAME also deals with these. We should ensure the "manifestations" are what we do here.

**Comment by opoudjis** [comment]
`medium/form` is modelled is free text, and in general can only be modelled as free text. I'll insert a note that it can include the distinction electronic vs paper.

**Comment by opoudjis** [comment]
I'm retaining electronic_resource as a legacy encoding (this is meant to be an encoding of ISO 690), but I am adding website as a type, with an annotation that electronic_resources are properly encoded through medium/form.

**Comment by ronaldtse** [comment]
Now that the editing of ISO 690 DIS is complete I can confirm that a website can be modeled as a website there. Finally I can close this tab!
