### ISSUE TITLE
Refinement of genres in model

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-models#20]
See email discussion between @ronaldtse and me.

**Comment by opoudjis** [comment]
Hi Nick,

I have reservations on the abuse of "webresource". The usage of "webresource" is just like marking all types as "text".

The "web" has a specific meaning, which is accessible via the Internet. If the resource is available via a proprietary data protocol or even TCP, it does not fit "webresource".

Forums and blogs aren't so different from newspapers or magazines. So what is the bibtype of an issue of newspaper or magazine?

Direct messages are just like letters.

A status update is like an announcement. How do you cite an announcement, e.g. earthquake/tsunami warning?

Below I propose the the bibtypes in square brackets (the [OK] ones are agreed).

Ron


Aggregated text/computer/online resource:

* Online book: text/computer/online resource/book [OK]
* Online journal: text/computer/online resource/journal [OK]
* Manuscript transcription: text/computer/online resource/archival [OK]

* Website: text/computer/online resource/website [OK]
* Forum: text/computer/online resource/website [article collection?]
* Blog: text/computer/online resource/website [series?]
* Twitter page: text/computer/online resource/website [web service?]


Atomic text/computer/online resource:

* Webpage: text/computer/online resource/webresource [webpage]
* Facebook post: text/computer/online resource/webresource [article or message]
* Forum post: text/computer/online resource/webresource [article]
* Blog post: text/computer/online resource/webresource [article]
* Tweet: text/computer/online resource/webresource [broadcast message]
* Facebook status update: text/computer/online resource/webresource [broadcast message]
* WeChat post: text/computer/online resource/webresource [broadcast message]

* Facebook Direct Message: text/computer/online resource/misc (message) [private message]
* Skype Direct Message: text/computer/online resource/misc (message) [private message]
* WhatsApp/WeChat/Messenger etc: [private message]

Others:

* Skype Call: spoken word/computer/online resource/misc (message) [conversation]
* Physical book: text/unmediated/volume/book [OK]
* Physical journal: text/unmediated/volume/journal [OK]
* Physical video: two-dimensional moving image/video/videodisc/video [OK]
* Physical image: still image/unmediated/sheet/graphic work [OK]
* Physical audio (CD): performed music/audio/audio disc/music [OK]
* Physical audio (music score): notated music/unmediated/volume/music [music score?]
* Online video: two-dimensional moving image/computer/online resource/video [OK]
* Online image: still image/computer/online resource/graphic work [OK]
* Online audio: performed music/computer/online resource/music [OK]
* Online music score: notated music/computer/online resource/music [music score?]
* Manuscript: text/unmediated/volume/archival
* Manuscript digitisation: still image/computer/online resource/archival
* Dataset: computer dataset/computer/online resource/dataset

**Comment by opoudjis** [comment]
I have to reject the suggestion that we reclassify social media as the equivalent of journal articles.

> Forums and blogs aren't so different from newspapers or magazines. So what is the bibtype of an issue of newspaper or magazine?

The `bibitem/@type` attribute, like the entry type in BibTex, and equivalent types in other biblio software, is used to chose the style of citation of the work. An electronic book citation can look pretty much the same as a paper book citation. But the citation of a blog looks *nothing* like the citation of a magazine, newspaper, or journal, and it would be extremely misleading to use those type attributes.

I accept that web resource should be restricted to resources accessed on the web. But given that ISO 690 are treating social media as their own class for citations (and I can see why—authorship there is much more dynamic and granular), I propose to elevate `social media` to a bibtype: it is more useful to conflate Facebook posts and status updates as the one bibtype (and citation template), than to differentiate them.

I will add, with some reluctance, the bibtypes `alert` (broadcast message risks confusion with radio), `message`, and `conversation`.

**Comment by ronaldtse** [comment]
> The bibitem/@type attribute, like the entry type in BibTex, and equivalent types in other biblio software, is used to chose the style of citation of the work. An electronic book citation can look pretty much the same as a paper book citation. But the citation of a blog looks nothing like the citation of a magazine, newspaper, or journal, and it would be extremely misleading to use those type attributes.

I suspect that a `blog` should just be called a blog because everyone understands it.

> I accept that web resource should be restricted to resources accessed on the web. But given that ISO 690 are treating social media as their own class for citations (and I can see why—authorship there is much more dynamic and granular), I propose to elevate `social media` to a bibtype: it is more useful to conflate Facebook posts and status updates as the one bibtype (and citation template), than to differentiate them.

What is `social media` though? There is no clear definition for what it is.

**Comment by opoudjis** [comment]
I have provided a definition of social media in the document, as one or more collectively authored online resources, and I would rather not proliferate the bibtypes to some unwieldy laundry list of everything, when the entire point of bibtype is that it is a restricted list that determines the citation format. If I add blog, I will have to add forum, and app, and Facebook, and Twitter. No. ISO 690 treats social media as a single distinct citable category, and the proposal has done the same.
