### ISSUE TITLE
SpecificLocalityType extensions

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#24]
In ITU an Annex can be a separate document.

In IHO these can be separate documents:
* Annex
* Section of Annex
* Appendix
* Annex of Appendix
* Annex of Chapter of Appendix

This means we need to extend SpecificLocalityType with:
* appendix (i.e. refering to another document as an appendix)
* document (i.e. I am "document B", but I am an appendix of "document A")

Please tell me if this makes sense...

Ping @opoudjis @andrew2net .

**Comment by ronaldtse** [comment]
See https://github.com/metanorma/metanorma-model-iho

**Comment by opoudjis** [comment]
The requested extensions are all there in Locality. But the UML needs correction:

* The hierarchy of localities needs to be separated from the multiplicity of localities
* The order sensitivity of the localities in hierarchical listing needs to be indicated (?)
* Source and target localities need to be differentiated for relations, with the default being target
* Update documentation in csd-citation-models

**Comment by ronaldtse** [comment]
We've decided that DocumentRelation works since it already include `bibLocality[0..*]`.

This is how we will model a document being an "Appendix 2 of Chapter 3 of Annex A of Doc 123":

```xml
<locality>
  <referenceFrom type="appendix">2</referenceFrom>
  <referenceFrom type="chapter">3</referenceFrom>
  <referenceFrom type="annex">A</referenceFrom>
</locality>
<bibItem>... of Doc 123 ... </bibItem>
```

The bibLocality set will need to be an ordered one (need to reflect in UML) to reflect hierarchy. Need to differentiate with sibling relationships.

DocumentRelationship needs to be updated to distinguish source and target locality.

In the bottom-up fashion, a document node specifies its relationship to the top-level (if it has one) via document relationships (i.e. child-to-parent relationships).

In a top-level document, as the aggregator, it specifies absolute relationships about its inner components (including documents that belongs to it). This aggregator can override relationships defined in inner nodes.

Changes here are already reflected in https://github.com/metanorma/metanorma-model-iho/commit/24a71fa3eea697a52e60c4c49794a4bbd9c1ee58 .

**Comment by opoudjis** [comment]
No, bigger to smaller, as has ALWAYS been the case in Relaton.

````
<locality type="chapter">
  <referenceFrom>3</referenceFrom>
</locality>
<locality type="appendix">
  <referenceFrom>2</referenceFrom>
</locality>
<locality type="annex">
  <referenceFrom>A</referenceFrom>
</locality>
<bibItem>... of Doc 123 ... </bibItem>
````

**Comment by ronaldtse** [comment]
Fine. Chill out, it's just Monday.
