### ISSUE TITLE
Addition: relation/description, sourceLocation, LocationStack, sourceLocationStack

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-models#25]
In response to discussion at #22 and #24, I am introducing two refinements to the relaton document model. @andrew2net, you will have to implement these in relaton.

`relation` currently has as its children `bibitem` and `locality`. We are adding two more children, and redefining one.

* `description` allows an elaboration of the relation specified in `relation/@type`, just as `role/description` elaborates on the relation specified in `role/@type`

* Until now, multiple locality elements allow us to hierarchically specify a single locality in a text; e.g. 

````
<locality type="chapter"><referenceFrom>3</referenceFrom></locality>
<locality type="page"><referenceFrom>32</referenceFrom></locality>
<locality type="line"><referenceFrom>7</referenceFrom><referenceTo>9</referenceTo></locality>
````

= Ch. 3, p. 32, ll. 7-9

We have also implicitly allowed discontinuous citations if they repeat the type:

````
<locality type="chapter"><referenceFrom>3</referenceFrom></locality>
<locality type="chapter"><referenceFrom>5</referenceFrom></locality>
````

= Ch. 3, 5

But in relations, we potentially have more complex discontinuous parts of the text; so it is necessary to group together locations as belonging to the one hierarchical specification of text, more rigorously than in citations. 

So we will introduce the element locationStack, which is a wrapper around locations that belong together hierarchically. 

````
<localityStack>
<locality type="chapter"><referenceFrom>3</referenceFrom></locality>
<locality type="page"><referenceFrom>32</referenceFrom></locality>
<locality type="line"><referenceFrom>7</referenceFrom><referenceTo>9</referenceTo></locality>
</localityStack>
<localityStack>
<locality type="chapter"><referenceFrom>5</referenceFrom></locality>
</localityStack>
````

If the wrapper is absent, then the locations are assumed to all specify the one location hierarchically—except where the type remains the same, in which case they are taken as specifying a discontinuous range. (i.e. behaviour as before.)

And the definition of either a citation or a relation involves:

````
citation = element citation {
  attribute bibitemid,
  (locality* | localitystack *),
  date?
}

localitystack = element localitystack {
locality*
}

locality = element locality {
attribute type { LocalityType },
    referenceFrom?, referenceTo?
}
````

* `sourceLocationStack` and `sourceLocation` specifies the location in the source document to which the relation applies, just as `locationStack` and `location` specifies the location in the target document to which the relation applies.

````
<relation type="derivedFrom">
  <description>isProfileOf</description>
  <bibitem>(bibliographic entry)</bibitem>
  <locality type="appendix">
    <referenceFrom>2</referenceFrom>
  </locality>
  <locality type="chapter">
    <referenceFrom>3</referenceFrom>
  </locality>
  <locality type="annex">
    <referenceFrom>A</referenceFrom>
  </locality>
  <sourceLocality type="chapter">
    <referenceFrom>2</referenceFrom>
  </sourceLocality>
</relation>
````

**Comment by opoudjis** [comment]
In relaton, use locationStack and sourceLocationStack; the versions of just repeating location and sourceLocation are intended for backward compatibility.

**Comment by ronaldtse** [comment]
Looks good to me.

**Comment by opoudjis** [comment]
@Intelligent2013 If there are two instances of LocalityStack in a citation, delimit them by "; ". All instances of Locality will now come wrapped in LocalityStack.
