### ISSUE TITLE
Need adding series/issn element.

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-models#28]
Files in the [relaton-data-iho](https://github.com/relaton/relaton-data-iho) contain `series/issn`. We need to add this new element to the grammar.

**Comment by ronaldtse** [comment]
This seems to be additional document identifiers. ISSN, ISBN, etc. A document surely has to allow multiple document identifiers.

**Comment by opoudjis** [comment]
A document already does allow multiple document identifiers, and there is absolutely zero need to add `issn` as a distinct element. An ISSN is merely `<docidentifier type="ISSN">`

At issue here is whether series elements should be given their own document identifiers, or whether the ISSN series that a document belongs to should be moved to where all the other document identifiers already are. https://www.relaton.com/specs/model/identifiers/ explicity recommends the latter:

> The namespace of an identifier is indicated through its type attribute. The scope of an identifier is introduced to disambiguate the identifier referent, when it is not obvious. So it is introduced where an identifier identifies only a component of the item (e.g. a document included in the item), or a superset of the item (e.g. a series).

So mark this up as `<docidentifier type="ISSN" scope="series">`. Compare the example at the bottom of that page:

````
<bibitem type="article">
<title>International Journal of Islamic Thought</title>
<docidentifier scope="journal" type="doi">10.24035/ijit</docidentifier>
<docidentifier scope="article" type="doi">https://doi.org/10.24035/ijit.14.2018.001</docidentifier>
</bibitem>
````

**Comment by opoudjis** [comment]
Of course, what I don't know @andrew2net is whether you've already implemented the scope attribute, as we have not invoked it to date. But it's been in the grammar for a while, for this reason.

**Comment by andrew2net** [comment]
@opoudjis scope isn't implemented yet
