### ISSUE TITLE
Convert models to LutaML-UML format

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#30]
We need to convert all models to the LutaML-UML format.

Install via: `gem install lutaml`

The syntax is described here:
https://github.com/lutaml/lutaml-uml/blob/master/LUTAML.adoc

And there is a migration command from PlantUML WSD to LutaML, `lutaml-wsd2uml [file]`

**Comment by andrew2net** [comment]
@ronaldtse I've bumped to an issue. Lutaml raises an error because of sybol `/`. Do you have any suggestion how to address it?
```
  enum StringFormat {
      text/plain
      text/html
      application/docbook+xml
      application/tei+xml
      text/x-asciidoc
      text/markdown
      application/x-isodoc+xml
  }
```
```
lutaml -t png -o ./images/ models/RelBib_DocumentRelation.lutaml
/Users/andrej/.rvm/gems/ruby-2.4.0/gems/parslet-1.7.1/lib/parslet/cause.rb:70:in `raise': Failed to match sequence (WHITESPACE? DIAGRAM_DEFINITION) at line 1 char 1. (Parslet::ParseFailed)
        from /Users/andrej/.rvm/gems/ruby-2.4.0/gems/parslet-1.7.1/lib/parslet/atoms/base.rb:49:in `parse'
...
```

**Comment by ronaldtse** [comment]
Could you try double quotes?

Ping @w00lf , is this supported in lutaml-uml?

**Comment by w00lf** [comment]
> Could you try double quotes?
> 
> Ping @w00lf , is this supported in lutaml-uml?

Yes, its supported but in this case we don't support `/` char at all, I will create a hotfix

**Comment by ronaldtse** [comment]
Thank you @w00lf!

**Comment by w00lf** [comment]
@andrew2net @ronaldtse added support for slash chars, released the new lutaml-uml version - 0.2.10

**Comment by andrew2net** [comment]
thank you @w00lf, now if there is a symbol "+" in value then it's rendered in a new line:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/5623890/111464979-ce50bb80-8721-11eb-8b1b-aeea6d1fed62.png">

**Comment by andrew2net** [comment]
@ronaldtse, @w00lf it seems multiple types not allowed. This class raises an error:
```
  class DocumentRelation {
      +type: DocumentRelationType
      +description: FormattedString[0..*]
      +bibitem: BibliographicItem
      +bibLocality: BibItemLocality[0..*] | LocalityStack[0..*]
      +bibSourceLocality: BibItemLocality[0..*]  | LocalityStack[0..*]
  }
```

**Comment by w00lf** [comment]
> thank you @w00lf, now if there is a symbol "+" in value then it's rendered in a new line:
> 
> <img alt="image" width="202" src="https://user-images.githubusercontent.com/5623890/111464979-ce50bb80-8721-11eb-8b1b-aeea6d1fed62.png">

@andrew2net can you supply the original lutaml code for debuging?

**Comment by w00lf** [comment]
> @ronaldtse, @w00lf it seems multiple types not allowed. This class raises an error:
> 
> ```
>   class DocumentRelation {
>       +type: DocumentRelationType
>       +description: FormattedString[0..*]
>       +bibitem: BibliographicItem
>       +bibLocality: BibItemLocality[0..*] | LocalityStack[0..*]
>       +bibSourceLocality: BibItemLocality[0..*]  | LocalityStack[0..*]
>   }
> ```

Multiple types don't supported yet

**Comment by andrew2net** [comment]
> @andrew2net can you supply the original lutaml code for debuging?

@w00lf 
```
enum StringFormat {
      text/plain
      text/html
      application/docbook+xml
      application/tei+xml
      text/x-asciidoc
      text/markdown
      application/x-isodoc+xml
  }
```

**Comment by andrew2net** [comment]
we wait for the multitype implementation https://github.com/lutaml/lutaml-uml/issues/79

**Comment by w00lf** [comment]
> > @andrew2net can you supply the original lutaml code for debuging?
> 
> @w00lf
> 
> ```
> enum StringFormat {
>       text/plain
>       text/html
>       application/docbook+xml
>       application/tei+xml
>       text/x-asciidoc
>       text/markdown
>       application/x-isodoc+xml
>   }
> ```

Fixed in https://github.com/lutaml/lutaml-uml/pull/81

**Comment by ronaldtse** [comment]
I've already converted all the files, all working now.
