### ISSUE TITLE
Split Relaton flavor models into separate repositories, in LutaML format

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#34]
We need to split all the Relaton flavor models into their own repository, and all files in the LutaML format.

* [x] Extract 3GPP bibliographic models from metanorma-model-iso to relaton-model-3gpp
* [x] Extract BIPM bibliographic models from metanorma-model-iso to relaton-model-bipm
* [x] Extract BSI bibliographic models from metanorma-model-iso to relaton-model-bsi
* [x] Extract CSA bibliographic models from metanorma-model-iso to relaton-model-csa
* [x] Extract GB bibliographic models from metanorma-model-iso to relaton-model-gb
* [x] Extract CC/CalConnect bibliographic models from metanorma-model-iso to relaton-model-cc
* [x] Extract IEC bibliographic models from metanorma-model-iso to relaton-model-iec
* [x] Extract IETF bibliographic models from metanorma-model-iso to relaton-model-ietf
* [x] Extract IHO bibliographic models from metanorma-model-iso to relaton-model-iho
* [x] Extract ISO bibliographic models from metanorma-model-iso to relaton-model-iso
* [x] Extract ITU bibliographic models from metanorma-model-iso to relaton-model-itu
* [x] Extract M3AAWG bibliographic models from metanorma-model-iso to relaton-model-m3aawg
* [x] Extract MPFA bibliographic models from metanorma-model-iso to relaton-model-mpfa
* [x] Extract NIST bibliographic models from metanorma-model-iso to relaton-model-nist
* [x] Extract OGC bibliographic models from metanorma-model-iso to relaton-model-ogc
* [x] Extract Ribose bibliographic models from metanorma-model-iso to relaton-model-ribose
* [x] Extract UN bibliographic models from metanorma-model-iso to relaton-model-un

**Comment by andrew2net** [comment]
@opoudjis has done this

**Comment by opoudjis** [comment]
And I will take credit for it. :)
