### ISSUE TITLE
Clarify which standard should `LocalizedString.language` conform to

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-models#40]
https://github.com/relaton/relaton-models/blob/e68ae6c09d5ef9040e263933efb9c1d577c54c47/models/LocalizedString.lutaml#L5-L9

It specifies ISO 639, but we should probably narrow it down to 639-1, 639-2/B or 639-3. I assume it should be 639-2/B?

**Comment by strogonoff** [comment]
Actually, it explicitly says:

https://github.com/relaton/relaton-models/blob/e68ae6c09d5ef9040e263933efb9c1d577c54c47/models/Iso639Code.lutaml#L1-L7

So I guess not.

**Comment by opoudjis** [comment]
The spec is open about this on purpose, because we've been using 639-1. It would be significant re-eengineering to switch to 639-2, and I'd rather avoid it.
