### ISSUE TITLE
Put the release version into grammar file

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-models#47]
To exclude a human factor I suggest putting the release number into biblio.rng file as a comment.
The relaton-bib contains a copy of the grammar for output testing so that the relaton-bib can use the release number to render in bibdata/@schema-version attribute.

**Comment by opoudjis** [comment]
Current git tags are output to grammars/version.json, generated by grammars/make.sh:

````
{
"relaton-models": "v1.2.0",
"basicdoc-models": "v1.0.0",
"metanorma-requirements-models": "v1.0.0",
"relaton-model-ieee": "v1.0.0",
"relaton-model-iso": "v1.0.0",
"relaton-model-iec": "v1.0.0",
"relaton-model-bsi": "v1.0.0",
"relaton-model-gb": "v1.0.0",
"relaton-model-mpfa": "v1.0.0",
"relaton-model-bipm": "v1.0.0",
"relaton-model-w3c": "v1.0.0",
"relaton-model-3gpp": "v1.0.0",
"relaton-model-csa": "v1.0.0",
"relaton-model-cc": "v1.0.0",
"relaton-model-ietf": "v1.0.0",
"relaton-model-iho": "v1.0.0",
"relaton-model-itu": "v1.0.0",
"relaton-model-m3aawg": "v1.0.0",
"relaton-model-nist": "v1.0.0",
"relaton-model-ribose": "v1.0.0",
"relaton-model-ogc": "v1.0.1",
"relaton-model-un": "v1.0.0",
"date": "2022-11-16T13:09:23Z"
}
````

As already indicated, the value of `relaton-models` goes into `bibitem/@schema-version`, and the value of `relaton-models-*` goes to `bibitem/ext/@schema-version`.
