### ISSUE TITLE
Missing `isPreprintOf` relationship type

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#48]
From @andrew2net https://github.com/relaton/relaton-nist/issues/84#issuecomment-1688957209

> we don't have isPreprintOf in relaton grammar. We use reprintOf instead.

**Comment by opoudjis** [comment]
A preprint is a draft, since it is not the official published version. Therefore, it is covered by isDraftOf, maybe with stage = preprint.

No. You cannot just add an extra relation.

**Comment by ronaldtse** [comment]
@opoudjis so why do we have "reprintOf" in addition to "manifestationOf"?

https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/models/DocumentRelationType.lutaml#L97-L102

**Comment by ronaldtse** [comment]
We do have "preprint" covered under "draft":
https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/models/DocumentRelationType.lutaml#L207-L222

The "preprint" is also covered under DocumentStatus.stage:

https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/models/DocumentStatus.lutaml#L7

**Comment by opoudjis** [comment]
> @opoudjis so why do we have "reprintOf" in addition to "manifestationOf"?
> 
> https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/models/DocumentRelationType.lutaml#L97-L102

manifestation is a generic FRBR relation; reprint is the very specific relation of a print republication with identical content. Preprints are not reprints; reprints presuppose that there is a published original, preprints are drafts preceding a publication.
