### ISSUE TITLE
Adding logos to things

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-models#49]
Since we added logos to organizations (https://github.com/metanorma/metanorma-nist/issues/103), shouldn't we allow previews (e.g. cover) to be added to the bib item itself?

**Comment by opoudjis** [comment]
Let's see what the precedent is out there in biblio models; I suspect it is done.

**Comment by opoudjis** [comment]
Bibframe has https://id.loc.gov/ontologies/bibframe.html#c_CoverArt: "Cover illustration of a resource"

BIBO has https://dcmi.github.io/bibo/#foaf:depiction, which is applicable to Agents; Agents in FOAF can include resources

Nothing obvious in MARC. 

I think the case is strong enough, but I'm going to make it open-ended by calling the field `depiction`, and not restricting it to cover art.

**Comment by ronaldtse** [comment]
But that would allow people to insert inner page previews as well?

**Comment by opoudjis** [comment]
I'm letting it be open-ended. I'll add typing on the wrapper.

**Comment by opoudjis** [comment]
````
class Depiction {
  definition {
    Depiction of the bibliographic item.
  }
  +scope: String[0..1] {
    definition {
      Description of what is being depicted
    }
  }
  +image: <<Basicdoc>>Image[0..*] {
    definition {
      A visual depiction of the bibliographic item.
    }
  }
}
````

**Comment by ronaldtse** [comment]
Thank you!
