### ISSUE TITLE
Title variants

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-models#54]
Title's content was ForamttedString before, which can contain variants of localized string. It is used in IHO currently (maybe somewhere else)
```yam
...
series:
  number: B
  type: main
  title:
    type: original
    content:
    - content: Bathymetric Publications
      language: en
      script: Latn
    - content: Publications bathymétriques
      language: fr
      script: Latn
...
```
We can't have content variant in titles now, and series doesn't allow more than 1 title.

**Comment by opoudjis** [comment]
I had refactored the grammar to use formatting in titles, but that has ended up removing the idiosyncratically provided `variant` tag, which allowed metadata to provide language-specific variants: `<title><variant lang="en">...</variant><variant lang="fr">...</variant></title>`

We sidestep this facility in bibitem/title, which allows multiple titles, differentiated by language as well as type. We are constraining series to have a single title. But relaxing that constraint on series, so it can have multiple titles differentiated by language, is not really solving the issue. Variants are still useful to be supported.

If we re-introduce variants, variants do need to incorporate Metanorma markup: we need to be able to do not just 

````
<title>person<sub>1</sub> and person<sub>2</sub></title>
````

but 

````
<title>
<variant lang="en">person<sub>1</sub> and person<sub>2</sub></variant>
<variant lang="fr">personne<sub>1</sub> et personne<sub>2</sub></variant>
</title>
````

**Comment by opoudjis** [comment]
@andrew2net The base issue here will be addressed by https://github.com/relaton/relaton-models/issues/55
