### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [relaton/relaton-models#7]
Convert Relation Bibliographic StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.

- [PNG.zip](https://github.com/riboseinc/bib-models/files/2335872/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/bib-models/files/2335873/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/bib-models/files/2335874/SVG.zip)

**Comment by ronaldtse** [comment]
Thanks @VasBu !

Uploaded to repo in f912e6d. Closing.
